//Login using email id details actions
export const EMAIL_LOGIN_START = "EMAIL_LOGIN_START";
export const EMAIL_LOGIN_SUCCESS = "EMAIL_LOGIN_SUCCESS";
export const EMAIL_LOGIN_ERROR = "EMAIL_LOGIN_ERROR";
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const FORGOT_PASSWORD_START = "FORGOT_PASSWORD_START";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

// student action
export const ADD_STUDENT_START = "ADD_STUDENT_START";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_ERROR = "ADD_STUDENT_ERROR";

export const GET_ALL_STUDENTS_DATA_START = "GET_ALL_STUDENTS_DATA_START";
export const GET_ALL_STUDENTS_DATA_SUCCESS = "GET_ALL_STUDENTS_DATA_SUCCESS";
export const GET_ALL_STUDENTS_DATA_ERROR = "GET_ALL_STUDENTS_DATA_ERROR";

export const UPDATE_STUDENTS_START = "UPDATE_STUDENTS_START";
export const UPDATE_STUDENTS_SUCCESS = "UPDATE_STUDENTS_SUCCESS";
export const UPDATE_STUDENTS_ERROR = "UPDATE_STUDENTS_ERROR";

export const DELETE_STUDENTS_START = "DELETE_STUDENTS_START";
export const DELETE_STUDENTS_SUCCESS = "DELETE_STUDENTS_SUCCESS";
export const DELETE_STUDENTS_ERROR = "DELETE_STUDENTS_ERROR";

// teaching staff
export const ADD_TEACHING_STAFF_START = "ADD_TEACHING_STAFF_START";
export const ADD_TEACHING_STAFF_SUCCESS = "ADD_TEACHING_STAFF_SUCCESS";
export const ADD_TEACHING_STAFF_ERROR = "ADD_TEACHING_STAFF_ERROR";

export const GET_ALL_TEACHING_STAFF_DATA_START = "GET_ALL_TEACHING_STAFF_DATA_START";
export const GET_ALL_TEACHING_STAFF_DATA_SUCCESS = "GET_ALL_TEACHING_STAFF_DATA_SUCCESS";
export const GET_ALL_TEACHING_STAFF_DATA_ERROR = "GET_ALL_TEACHING_STAFF_DATA_ERROR";

export const UPDATE_TEACHING_STAFF_START = "UPDATE_TEACHING_STAFF_START";
export const UPDATE_TEACHING_STAFF_SUCCESS = "UPDATE_TEACHING_STAFF_SUCCESS";
export const UPDATE_TEACHING_STAFF_ERROR = "UPDATE_TEACHING_STAFF_ERROR";

export const DELETE_TEACHING_STAFF_START = "DELETE_TEACHING_STAFF_START";
export const DELETE_TEACHING_STAFF_SUCCESS = "DELETE_TEACHING_STAFF_SUCCESS";
export const DELETE_TEACHING_STAFF_ERROR = "DELETE_TEACHING_STAFF_ERROR";
// user profile
export const GET_USER_PROFILE_START = "GET_USER_PROFILE_START";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR";

export const UPDATE_USER_PROFILE_START = "UPDATE_USER_PROFILE_START";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_ERROR = "UPDATE_USER_PROFILE_ERROR";

// add class
export const ADD_CLASS_START = "ADD_CLASS_START";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_ERROR = "ADD_CLASS_ERROR";

export const GET_ALLCLASSES_START = "GET_ALLCLASSES_START";
export const GET_ALLCLASSES_SUCCESS = "AGET_ALLCLASSES_SUCCESS";
export const GET_ALLCLASSES_ERROR = "GET_ALLCLASSES_ERROR";

export const DELETE_CLASS_START = "DELETE_CLASS_START";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_ERROR = "DELETE_CLASS_ERROR";

export const EDIT_CLASS_START = "EDIT_CLASS_START";
export const EDIT_CLASS_SUCCESS = "EDIT_CLASS_SUCCESS";
export const EDIT_CLASS_ERROR = "EDIT_CLASS_ERROR";

export const ADD_CLASSTIMETABLE_START = "ADD_CLASSTIMETABLE_START";
export const ADD_CLASSTIMETABLE_SUCCESS = "ADD_CLASSTIMETABLE_SUCCESS";
export const ADD_CLASSTIMETABLE_ERROR = "ADD_CLASSTIMETABLE_ERROR";

export const GET_CLASSTIMETABLE_START = "GET_CLASSTIMETABLE_START";
export const GET_CLASSTIMETABLE_SUCCESS = "GET_CLASSTIMETABLE_SUCCESS";
export const GET_CLASSTIMETABLE_ERROR = "GET_CLASSTIMETABLE_ERROR";

export const DELETE_CLASSTIMETABLE_START = "DELETE_CLASSTIMETABLE_START";
export const DELETE_CLASSTIMETABLE_SUCCESS = "DELETE_CLASSTIMETABLE_SUCCESS";
export const DELETE_CLASSTIMETABLE_ERROR = "DELETE_CLASSTIMETABLE_ERROR";

export const UPDATE_CLASSTIMETABLE_START = "UPDATE_CLASSTIMETABLE_START";
export const UPDATE_CLASSTIMETABLE_SUCCESS = "UPDATE_CLASSTIMETABLE_SUCCESS";
export const UPDATE_CLASSTIMETABLE_ERROR = "UPDATE_CLASSTIMETABLE_ERROR";